### PR TITLE
Various fixes relating to Xcode 7, xcconfig support, test failure, etc.

### PR DESCRIPTION
**Pull request by cezheng**
I'm using XcodeEditor for a Commandline tool(in Swift) I make for my employer, and I have made following changes.

* 
* Included all necessary headers in the umbrella header XcodeEditor.h for Swift https://github.com/appsquickly/XcodeEditor/commit/0de406ff80d36961c70170d304d406ffe0652e06 https://github.com/appsquickly/XcodeEditor/commit/cd1e757e3630de9facccbbeb0a54045626652b2d https://github.com/appsquickly/XcodeEditor/commit/e13d916487b9f4d9a5096ca391b80277f9b2269b
* Move some resource files for test out from framework target to test target https://github.com/appsquickly/XcodeEditor/commit/7ef4a5d509539e3f5e9b4b4d2a2dc7799445e1eb
* Add XCConfig to XcodeSourceFileType (*.xcconfig) https://github.com/appsquickly/XcodeEditor/commit/9e30fee3d12806e0f3734d6a690779fdcb2c6c8c
* Bug fix https://github.com/appsquickly/XcodeEditor/commit/53e1c875b3eb1661cbd466f08b4a55ddf9b0b3ea
* Log output behaviour changes https://github.com/appsquickly/XcodeEditor/commit/0df67a8c672c3ffbd79ca89873f47eb31b9a1669
* Xcode 7.1 adjustment & fix https://github.com/appsquickly/XcodeEditor/commit/39310d5815bff7bda483a372242f3d13642d6e57 https://github.com/appsquickly/XcodeEditor/commit/e350b5fb92aae39e635f160553c4e980197c0812

### CODE REVIEW

**Comment by jasperblues** [comment]
@cezheng Thanks for your contribution! These look good. Would you like us to add you to the readme as a contributor.

**Comment by cezheng** [comment]
@jasperblues wow, thanks for the quick merge. Yes if you don't mind:smile:

**Comment by jasperblues** [comment]
Readme credits added!

**Comment by cezheng** [comment]
@jasperblues  Thanks for credit & for this library which saved me so much time:smile:

**Comment by jasperblues** [comment]
@cezheng :) :bow: Nice to work with you.

**Pull request merged**
